# Generated by Django 6.0.4 on 2026-04-15 08:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('video_file', models.FileField(upload_to='uploads/videos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('is_fake', models.BooleanField(blank=True, null=True)),
                ('heatmap_result', models.ImageField(blank=True, null=True, upload_to='results/heatmaps/')),
            ],
        ),
    ]
