# Generated by Django 6.0.4 on 2026-04-16 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectiontask',
            name='content_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='detectiontask',
            name='is_fake',
            field=models.BooleanField(default=False),
        ),
    ]
