# Generated by Django 6.0.4 on 2026-04-16 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0002_detectiontask_content_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim', models.TextField()),
                ('verdict', models.CharField(max_length=20)),
                ('score', models.FloatField()),
                ('reasoning', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
