# Generated by Django 6.0.4 on 2026-04-17 11:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0003_textverification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TextVerification',
        ),
        migrations.AddField(
            model_name='detectiontask',
            name='reasoning',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
